import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body>
        <header>
          <nav>
            <ul>
              <li><a href="/">Home</a></li>
              <li><a href="https://github.com/tu-usuario">GitHub</a></li>
              <li><a href="https://youtube.com/tu-canal">YouTube</a></li>
            </ul>
          </nav>
        </header>
        <main>{children}</main>
        <footer>
          <p>© 2024 Dataengjr - Todos los derechos reservados.</p>
        </footer>
      </body>
    </html>
  );
}
